// <auto-generated />
using System;
using ERPDotNet.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERPDotNet.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ERPDotNet.Application.Modules.ProductEngineering.Queries.GetWhereUsed.WhereUsedRecursiveResult", b =>
                {
                    b.Property<int>("BomHeaderId")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("UsageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("WhereUsedRecursiveResult");
                });

            modelBuilder.Entity("ERPDotNet.Domain.Common.AuditTrail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AffectedColumns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryKey")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.ToTable("audit_trails", "audit");
                });

            modelBuilder.Entity("ERPDotNet.Domain.Modules.BaseInfo.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descriptions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("SupplyType")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("UnitId");

                    b.ToTable("products", "base");
                });

            modelBuilder.Entity("ERPDotNet.Domain.Modules.BaseInfo.Entities.ProductUnitConversion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlternativeUnitId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Factor")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("AlternativeUnitId");

                    b.HasIndex("ProductId", "AlternativeUnitId")
                        .IsUnique();

                    b.ToTable("product_unit_conversions", "base");
                });

            modelBuilder.Entity("ERPDotNet.Domain.Modules.BaseInfo.Entities.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BaseUnitId")
                        .HasColumnType("int");

                    b.Property<decimal>("ConversionFactor")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Precision")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("BaseUnitId");

                    b.ToTable("units", "base");
                });

            modelBuilder.Entity("ERPDotNet.Domain.Modules.ProductEngineering.Entities.BOMDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BOMHeaderId")
                        .HasColumnType("int");

                    b.Property<int>("ChildProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("InputQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("InputUnitId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<byte[]>("RowVersion")
                        .HasColumnType("varbinary(max)");

                    b.Property<decimal>("WastePercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("ChildProductId");

                    b.HasIndex("InputUnitId");

                    b.HasIndex("BOMHeaderId", "ChildProductId")
                        .IsUnique();

                    b.ToTable("bom_details", "eng");
                });

            modelBuilder.Entity("ERPDotNet.Domain.Modules.ProductEngineering.Entities.BOMHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ToDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "Version")
                        .IsUnique();

                    b.ToTable("bom_headers", "eng");
                });

            modelBuilder.Entity("ERPDotNet.Domain.Modules.ProductEngineering.Entities.BOMSubstitute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BOMDetailId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Factor")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMixAllowed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MaxMixPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("SubstituteProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubstituteProductId");

                    b.HasIndex("BOMDetailId", "SubstituteProductId")
                        .IsUnique();

                    b.ToTable("bom_substitutes", "eng");
                });

            modelBuilder.Entity("ERPDotNet.Domain.Modules.UserAccess.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsMenu")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("permissions", "security");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsMenu = false,
                            Name = "System",
                            Title = "سیستم"
                        },
                        new
                        {
                            Id = 100,
                            IsMenu = true,
                            Name = "General",
                            ParentId = 1,
                            Title = "عمومی"
                        },
                        new
                        {
                            Id = 2,
                            IsMenu = true,
                            Name = "UserAccess",
                            ParentId = 100,
                            Title = "مدیریت کاربران",
                            Url = "/users"
                        },
                        new
                        {
                            Id = 3,
                            IsMenu = false,
                            Name = "UserAccess.View",
                            ParentId = 2,
                            Title = "مشاهده لیست"
                        },
                        new
                        {
                            Id = 4,
                            IsMenu = false,
                            Name = "UserAccess.Create",
                            ParentId = 2,
                            Title = "افزودن کاربر"
                        },
                        new
                        {
                            Id = 5,
                            IsMenu = false,
                            Name = "UserAccess.Edit",
                            ParentId = 2,
                            Title = "ویرایش کاربر"
                        },
                        new
                        {
                            Id = 6,
                            IsMenu = false,
                            Name = "UserAccess.Delete",
                            ParentId = 2,
                            Title = "حذف کاربر"
                        },
                        new
                        {
                            Id = 7,
                            IsMenu = true,
                            Name = "UserAccess.Roles",
                            ParentId = 100,
                            Title = "مدیریت نقش‌ها",
                            Url = "/roles"
                        },
                        new
                        {
                            Id = 8,
                            IsMenu = false,
                            Name = "UserAccess.Roles.Create",
                            ParentId = 7,
                            Title = "تعریف نقش"
                        },
                        new
                        {
                            Id = 9,
                            IsMenu = false,
                            Name = "UserAccess.Roles.Delete",
                            ParentId = 7,
                            Title = "حذف نقش"
                        },
                        new
                        {
                            Id = 10,
                            IsMenu = false,
                            Name = "UserAccess.Roles.Edit",
                            ParentId = 7,
                            Title = "ویرایش دسترسی‌ها"
                        },
                        new
                        {
                            Id = 11,
                            IsMenu = false,
                            Name = "UserAccess.SpecialPermissions",
                            ParentId = 2,
                            Title = "مدیریت دسترسی‌های ویژه"
                        },
                        new
                        {
                            Id = 90,
                            IsMenu = true,
                            Name = "General.Settings",
                            ParentId = 100,
                            Title = "تنظیمات سیستم",
                            Url = "/settings"
                        },
                        new
                        {
                            Id = 30,
                            IsMenu = true,
                            Name = "BaseInfo",
                            ParentId = 1,
                            Title = "اطلاعات پایه"
                        },
                        new
                        {
                            Id = 31,
                            IsMenu = true,
                            Name = "BaseInfo.Units",
                            ParentId = 30,
                            Title = "واحد سنجش",
                            Url = "/base-info/units"
                        },
                        new
                        {
                            Id = 32,
                            IsMenu = false,
                            Name = "BaseInfo.Units.Create",
                            ParentId = 31,
                            Title = "تعریف واحد"
                        },
                        new
                        {
                            Id = 33,
                            IsMenu = false,
                            Name = "BaseInfo.Units.Edit",
                            ParentId = 31,
                            Title = "ویرایش واحد"
                        },
                        new
                        {
                            Id = 34,
                            IsMenu = false,
                            Name = "BaseInfo.Units.Delete",
                            ParentId = 31,
                            Title = "حذف واحد"
                        },
                        new
                        {
                            Id = 35,
                            IsMenu = true,
                            Name = "BaseInfo.Products",
                            ParentId = 30,
                            Title = "مدیریت کالاها",
                            Url = "/base-info/products"
                        },
                        new
                        {
                            Id = 36,
                            IsMenu = false,
                            Name = "BaseInfo.Products.Create",
                            ParentId = 35,
                            Title = "تعریف کالا"
                        },
                        new
                        {
                            Id = 37,
                            IsMenu = false,
                            Name = "BaseInfo.Products.Edit",
                            ParentId = 35,
                            Title = "ویرایش کالا"
                        },
                        new
                        {
                            Id = 38,
                            IsMenu = false,
                            Name = "BaseInfo.Products.Delete",
                            ParentId = 35,
                            Title = "حذف کالا"
                        },
                        new
                        {
                            Id = 2000,
                            IsMenu = true,
                            Name = "ProductEngineering",
                            ParentId = 1,
                            Title = "مهندسی محصول"
                        },
                        new
                        {
                            Id = 200,
                            IsMenu = true,
                            Name = "ProductEngineering.BOM",
                            ParentId = 2000,
                            Title = "مدیریت BOM"
                        },
                        new
                        {
                            Id = 201,
                            IsMenu = true,
                            Name = "ProductEngineering.BOM.Create",
                            ParentId = 200,
                            Title = "تعریف BOM",
                            Url = "/product-engineering/boms"
                        },
                        new
                        {
                            Id = 202,
                            IsMenu = true,
                            Name = "ProductEngineering.BOM.Reports",
                            ParentId = 200,
                            Title = "گزارش BOM",
                            Url = "/product-engineering/boms"
                        });
                });

            modelBuilder.Entity("ERPDotNet.Domain.Modules.UserAccess.Entities.RolePermission", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions", "security");

                    b.HasData(
                        new
                        {
                            RoleId = "1",
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 10
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 100
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 90
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 30
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 31
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 32
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 33
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 34
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 35
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 36
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 37
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 38
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 2000
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 200
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 201
                        },
                        new
                        {
                            RoleId = "1",
                            PermissionId = 202
                        });
                });

            modelBuilder.Entity("ERPDotNet.Domain.Modules.UserAccess.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NationalCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonnelCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NationalCode")
                        .IsUnique()
                        .HasFilter("[NationalCode] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("users", "security");
                });

            modelBuilder.Entity("ERPDotNet.Domain.Modules.UserAccess.Entities.UserPermission", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsGranted")
                        .HasColumnType("bit");

                    b.HasKey("UserId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("user_permissions", "security");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("roles", "security");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            ConcurrencyStamp = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            ConcurrencyStamp = "2",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "3",
                            ConcurrencyStamp = "3",
                            Name = "Accountant",
                            NormalizedName = "ACCOUNTANT"
                        },
                        new
                        {
                            Id = "4",
                            ConcurrencyStamp = "4",
                            Name = "WarehouseKeeper",
                            NormalizedName = "WAREHOUSEKEEPER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("role_claims", "security");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_claims", "security");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("user_logins", "security");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", "security");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("user_tokens", "security");
                });

            modelBuilder.Entity("ERPDotNet.Domain.Modules.BaseInfo.Entities.Product", b =>
                {
                    b.HasOne("ERPDotNet.Domain.Modules.BaseInfo.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("ERPDotNet.Domain.Modules.BaseInfo.Entities.ProductUnitConversion", b =>
                {
                    b.HasOne("ERPDotNet.Domain.Modules.BaseInfo.Entities.Unit", "AlternativeUnit")
                        .WithMany()
                        .HasForeignKey("AlternativeUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERPDotNet.Domain.Modules.BaseInfo.Entities.Product", "Product")
                        .WithMany("UnitConversions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlternativeUnit");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ERPDotNet.Domain.Modules.BaseInfo.Entities.Unit", b =>
                {
                    b.HasOne("ERPDotNet.Domain.Modules.BaseInfo.Entities.Unit", "BaseUnit")
                        .WithMany()
                        .HasForeignKey("BaseUnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BaseUnit");
                });

            modelBuilder.Entity("ERPDotNet.Domain.Modules.ProductEngineering.Entities.BOMDetail", b =>
                {
                    b.HasOne("ERPDotNet.Domain.Modules.ProductEngineering.Entities.BOMHeader", "BOMHeader")
                        .WithMany("Details")
                        .HasForeignKey("BOMHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERPDotNet.Domain.Modules.BaseInfo.Entities.Product", "ChildProduct")
                        .WithMany()
                        .HasForeignKey("ChildProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERPDotNet.Domain.Modules.BaseInfo.Entities.Unit", "InputUnit")
                        .WithMany()
                        .HasForeignKey("InputUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BOMHeader");

                    b.Navigation("ChildProduct");

                    b.Navigation("InputUnit");
                });

            modelBuilder.Entity("ERPDotNet.Domain.Modules.ProductEngineering.Entities.BOMHeader", b =>
                {
                    b.HasOne("ERPDotNet.Domain.Modules.BaseInfo.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ERPDotNet.Domain.Modules.ProductEngineering.Entities.BOMSubstitute", b =>
                {
                    b.HasOne("ERPDotNet.Domain.Modules.ProductEngineering.Entities.BOMDetail", "BOMDetail")
                        .WithMany("Substitutes")
                        .HasForeignKey("BOMDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERPDotNet.Domain.Modules.BaseInfo.Entities.Product", "SubstituteProduct")
                        .WithMany()
                        .HasForeignKey("SubstituteProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BOMDetail");

                    b.Navigation("SubstituteProduct");
                });

            modelBuilder.Entity("ERPDotNet.Domain.Modules.UserAccess.Entities.Permission", b =>
                {
                    b.HasOne("ERPDotNet.Domain.Modules.UserAccess.Entities.Permission", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ERPDotNet.Domain.Modules.UserAccess.Entities.RolePermission", b =>
                {
                    b.HasOne("ERPDotNet.Domain.Modules.UserAccess.Entities.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ERPDotNet.Domain.Modules.UserAccess.Entities.UserPermission", b =>
                {
                    b.HasOne("ERPDotNet.Domain.Modules.UserAccess.Entities.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERPDotNet.Domain.Modules.UserAccess.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ERPDotNet.Domain.Modules.UserAccess.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ERPDotNet.Domain.Modules.UserAccess.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERPDotNet.Domain.Modules.UserAccess.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ERPDotNet.Domain.Modules.UserAccess.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ERPDotNet.Domain.Modules.BaseInfo.Entities.Product", b =>
                {
                    b.Navigation("UnitConversions");
                });

            modelBuilder.Entity("ERPDotNet.Domain.Modules.ProductEngineering.Entities.BOMDetail", b =>
                {
                    b.Navigation("Substitutes");
                });

            modelBuilder.Entity("ERPDotNet.Domain.Modules.ProductEngineering.Entities.BOMHeader", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("ERPDotNet.Domain.Modules.UserAccess.Entities.Permission", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
