import { MRT_Localization } from "mantine-react-table";

export const MRT_Localization_FA: MRT_Localization = {
  actions: "عملیات",
  and: "و",
  cancel: "انصراف",
  changeFilterMode: "تغییر حالت فیلتر",
  changeSearchMode: "تغییر حالت جستجو",
  clearFilter: "پاک کردن فیلتر",
  clearSearch: "پاک کردن جستجو",
  clearSort: "پاک کردن مرتب‌سازی",
  clickToCopy: "کپی",
  columnActions: "عملیات ستون",
  copiedToClipboard: "در حافظه کپی شد",
  collapse: "بستن",
  collapseAll: "بستن همه",
  dropToGroupBy: "کشیدن برای گروه‌بندی",
  edit: "ویرایش",
  expand: "باز کردن",
  expandAll: "باز کردن همه",
  filterArrIncludes: "شامل",
  filterArrIncludesAll: "شامل همه",
  filterArrIncludesSome: "شامل برخی",
  filterBetween: "بین",
  filterBetweenInclusive: "بین (شامل)",
  filterByColumn: "فیلتر ستون {column}",
  filterContains: "شامل",
  filterEmpty: "خالی",
  filterEndsWith: "پایان با",
  filterEquals: "مساوی",
  filterEqualsString: "مساوی",
  filterFuzzy: "تار (Fuzzy)",
  filterGreaterThan: "بزرگتر از",
  filterGreaterThanOrEqualTo: "بزرگتر مساوی",
  filterInNumberRange: "در بازه",
  filterIncludesString: "شامل",
  filterIncludesStringSensitive: "شامل (حساس به حروف)",
  filterLessThan: "کوچکتر از",
  filterLessThanOrEqualTo: "کوچکتر مساوی",
  filterMode: "حالت فیلتر: {filterType}",
  filterNotEmpty: "خالی نباشد",
  filterNotEquals: "نامساوی",
  filterStartsWith: "شروع با",
  filterWeakEquals: "مساوی",
  hideAll: "مخفی کردن همه",
  hideColumn: "مخفی کردن ستون {column}",
  max: "حداکثر",
  min: "حداقل",
  move: "جابجایی",
  noRecordsToDisplay: "هیچ رکوردی یافت نشد",
  noResultsFound: "نتیجه‌ای یافت نشد",
  of: "از",
  or: "یا",
  pinToLeft: "سنجاق به چپ",
  pinToRight: "سنجاق به راست",
  resetColumnSize: "بازنشانی عرض ستون",
  resetOrder: "بازنشانی ترتیب",
  rowActions: "عملیات سطر",
  rowNumber: "#",
  rowNumbers: "شماره ردیف",
  rowsPerPage: "تعداد در صفحه",
  save: "ذخیره",
  search: "جستجو",
  select: "انتخاب",
  selectedCountOfRowCountRowsSelected:
    "{selectedCount} از {rowCount} سطر انتخاب شده",
  showAll: "نمایش همه",
  showAllColumns: "نمایش تمام ستون‌ها",
  showHideColumns: "نمایش/مخفی کردن ستون‌ها",
  showHideFilters: "نمایش/مخفی کردن فیلترها",
  showHideSearch: "نمایش/مخفی کردن جستجو",
  sortByColumnAsc: "مرتب‌سازی صعودی {column}",
  sortByColumnDesc: "مرتب‌سازی نزولی {column}",
  sortedByColumnAsc: "مرتب شده صعودی بر اساس {column}",
  sortedByColumnDesc: "مرتب شده نزولی بر اساس {column}",
  thenBy: "سپس بر اساس",
  toggleDensity: "تغییر تراکم",
  toggleFullScreen: "تمام صفحه",
  toggleSelectAll: "انتخاب همه",
  toggleSelectRow: "انتخاب سطر",
  toggleVisibility: "تغییر نمایش",
  unpin: "لغو سنجاق",
  unpinAll: "لغو سنجاق همه",
  filteringByColumn: "فيلتر با ستون",
  goToFirstPage: "اولين صفحه",
  goToLastPage: "آخرين صفحه",
  goToNextPage: "صفحه بعد",
  goToPreviousPage: "صفحه قبل",
  grab: "",
  groupByColumn: "گروه با ستون",
  groupedBy: "گروه بندي",
  ungroupByColumn: "حذف گروه",
};
